[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
smallstr = { path = "../smallstr", features = [ "union", "deref_patterns" ] }
smallvec = { path = "../smallvec", features = [ "union", "const_generics", "const_new", "deref_pure_trait" ] }
derive_more = { version = "2", features = ["from", "display", "error"] }
nom = "8.0"
variantly = "0.4"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
